homepage: "https://www.cockroachlabs.com/"
language: go
primary_contact: "stan@cockroachlabs.com"
auto_ccs:
  - "test-eng@cockroachlabs.com"
main_repo: "https://github.com/cockroachdb/cockroach.git"
file_github_issue: true
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
