homepage: "https://surrealdb.com/"
language: rust
primary_contact: "tobie@surrealdb.com"
main_repo: "https://github.com/surrealdb/surrealdb"
auto_ccs:
  - security@surrealdb.com
  - finn.bear@surrealdb.com
  - salvador.girones@surrealdb.com
  - gerard.guillemas@surrealdb.com
  - mees.delzenne@surrealdb.com
  - emmanuel.keller@surrealdb.com
  - micha.de.vries@surrealdb.com
  - rushmore@surrealdb.com
  - nathaniel.brough@gmail.com

sanitizers:
  - address
fuzzing_engines:
  - libfuzzer

coverage_extra_args: >
  -ignore-filename-regex=.*/rustc/.*
