homepage: "https://buildwithmatter.com/"
language: c++
primary_contact: "andreilitvin@google.com"
auto_ccs:
  - "asad_haque@comcast.com"
  - "lalabdulkarim@csa-iot.org"
  - "mboyington@google.com"
  - "szewczyk@google.com"
  - "tennessee@google.com"
  - "aalami@csa-iot.org"
sanitizers:
  - address
  - undefined
  - memory
fuzzing_engines:
  - libfuzzer
  - honggfuzz
  - centipede
main_repo: 'https://github.com/project-chip/connectedhomeip.git'
